name = "Fabula"
license = "MIT License"
licenselink = "https://github.com/auspicus/hugo-theme-fabula/blob/master/LICENSE"
description = "Clean-shaven Hugo theme for journalism."
homepage = "https://github.com/auspicus/hugo-theme-fabula"
tags = ["journalism", "minimal", "minimalist"]
features = ["articles", "authors", "posts", "blogs"]
min_version = "0.30"

[author]
  name = "David Disch"
  homepage = "https://auspicus.io"