baseURL                     = "https://example.org/"        # Your domain name. Must end with "/"
languageCode                = "en-us"
title                       = "Fabula"                      # Site title
theme                       = "fabula"
pygmentsStyle               = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences          = true


[params]
description = "Clean-shaven Hugo theme for journalism."

[[params.social]]
url  = "https://twitter.com/"
icon = "twitter"

[[params.social]]
url  = "https://facebook.com/"
icon = "facebook"


[menu]

[[menu.main]]
name = "Categories"
weight = 1
identifier = "categories"
url = "/categories/"
