baseURL                     = "https://example.org/"        # Your domain name. Must end with "/"
languageCode                = "en-us"
title                       = "Bones"                       # Site title
theme                       = "bones"
pygmentsStyle               = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences          = true


[params]
description = "Skeleton of a Hugo theme."

[[params.social]]
url  = "https://twitter.com/"
icon = "twitter"

[[params.social]]
url  = "https://facebook.com/"
icon = "facebook"


[[menu.global]]
name = "News"
weight = 1
identifier = "news"
url = "/news/"
